In [1]:
import pandas as pd
import numpy as np
import random
from pprint import pprint

##dfreviews = pd.read_csv(r"C:\Users\danny\OneDrive\Desktop\yelp_review.csv")

In [7]:
pd.options.display.max_rows = None
pd.options.display.max_columns = None

In [2]:
df = pd.read_csv(r"C:\Users\danny\OneDrive\Desktop\yelp_business.csv")
df.head()

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,FYWN1wneV18bWNgQjJ2GNg,"""Dental by Design""",NaN,"""4855 E Warner Rd, Ste B9""",Ahwatukee,AZ,85044,33.330690,-111.978599,4.0,22,1,Dentists;General Dentistry;Health & Medical;Or...
1,He-G7vWjzVUysIKrfNbPUQ,"""Stephen Szabo Salon""",NaN,"""3101 Washington Rd""",McMurray,PA,15317,40.291685,-80.104900,3.0,11,1,Hair Stylists;Hair Salons;Men's Hair Salons;Bl...
2,KQPW8lFf1y5BT2MxiSZ3QA,"""Western Motor Vehicle""",NaN,"""6025 N 27th Ave, Ste 1""",Phoenix,AZ,85017,33.524903,-112.115310,1.5,18,1,Departments of Motor Vehicles;Public Services ...
3,8DShNS-LuFqpEWIp0HxijA,"""Sports Authority""",NaN,"""5000 Arizona Mills Cr, Ste 435""",Tempe,AZ,85282,33.383147,-111.964725,3.0,9,0,Sporting Goods;Shopping
4,PfOCPjBrlQAnz__NXj9h_w,"""Brick House Tavern + Tap""",NaN,"""581 Howe Ave""",Cuyahoga Falls,OH,44221,41.119535,-81.475690,3.5,116,1,American (New);Nightlife;Bars;Sandwiches;Ameri...

In [9]:
df['state'].unique()

array(['AZ', 'PA', 'OH', 'BW', 'NV', 'ON', 'NC', 'WI', 'SC', 'QC', 'IL',
       'MLN', 'EDH', 'FIF', 'CHE', 'CO', 'NYK', 'NE', 'HLD', 'WLN', 'ABE',
       'WA', 'SCB', 'KHL', 'ESX', 'CMA', 'FAL', 'ELN', 'NY', 'PKN', 'ST',
       '01', 'CA', 'NLK', 'GLG', 'C', 'VS', 'IN', 'XGL', 'AL', 'STG',
       'VT', 'CS', '30', 'AR', 'SL', 'NI', 'BY', 'AK', 'FLN', nan, 'FL',
       'MN', '6', 'NTH', 'MT', 'B', 'GA', 'VA', 'DE', 'AB', 'HU', 'KY',
       '3', 'TAM', 'ZET', 'RCC', 'WHT'], dtype=object)

In [10]:
df['city'].unique()

array(['Ahwatukee', 'McMurray', 'Phoenix', ...,
       'Henderson (Green Valley)', 'Side Slopes', 'Saint-Basile-Le-Grand'],
      dtype=object)

In [97]:
class Business:
    def __init__(self,business_id,name,address,city,state,postal_code,stars,review_count):
        self.business_id = business_id
        self.name = name
        self.address = address
        self.city = city
        self.state = state
        self.postal_code = postal_code
        self.stars = stars
        self.review_count = review_count


        
def get_star_business(businesses, rating):
    star_business = []
    for business in businesses:
        if business.stars >= rating:
            star_business.append(business)
    return star_business

def get_business_in_city(businesses, city):
    city_business = []
    for business in businesses:
        if business.city.lower() == city.lower():
            city_business.append(business)
    return city_business

def get_business_in_zipcode(businesses, zipcode):
    zipcode_business = []
    for business in businesses:
        if business.postal_code == zipcode:
            zipcode_business.append(business)
    return zipcode_business

columns = ['business_id', 'name', 'address', 'city', 'state', 'postal_code', 'stars', 'review_count']

dfbusiness = df[columns]

businesses = []

for index, row in dfbusiness.iterrows():
    business = Business(row['business_id'], row['name'], row['address'], str(row['city']), row['state'], row['postal_code'], row['stars'], row['review_count'])
    businesses.append(business)

rating = int(input("Enter the minimum rating of the business: "))
city = input("Enter the city of the business: ")
zipcode = input("Enter the zipcode of the business: ")

star_business = get_star_business(businesses, rating)
city_business = get_business_in_city(star_business, city)
zipcode_business = get_business_in_zipcode(city_business, zipcode)

random_business = random.sample(zipcode_business, 10)

print (f"10 RANDOM BUSINESSES WITH RATING >= {rating}, IN CITY: {city}, AND ZIPCODE: {zipcode}")
print ('----------')
for business in random_business[:10]:
    pprint(f"Name: {business.name}, Address: {business.address}, City: {business.city}, State: {business.state}, Postal code: {business.postal_code}, RATING: {business.stars}, Number of Reviews: {business.review_count}")

Enter the minimum rating of the business: 4
Enter the city of the business: Tempe
Enter the zipcode of the business: 85282
10 RANDOM RESTAURANTS WITH RATING >= 4, IN CITY: Tempe, AND ZIPCODE: 85282
----------
('Name: "Arizona Escapes", Address: "", City: Tempe, State: AZ, Postal code: '
 '85282, RATING: 5.0, Number of Reviews: 3')
('Name: "Pearl Nails & Spa", Address: "937 E Broadway Rd, Ste 6", City: Tempe, '
 'State: AZ, Postal code: 85282, RATING: 4.0, Number of Reviews: 127')
('Name: "Van Hook Dental Studio", Address: "2082 E Southern Ave, Ste F101", '
 'City: Tempe, State: AZ, Postal code: 85282, RATING: 5.0, Number of Reviews: '
 '3')
('Name: "The Platinum Spray Tan", Address: "1969 E Broadway Rd, Ste 8", City: '
 'Tempe, State: AZ, Postal code: 85282, RATING: 4.5, Number of Reviews: 69')
('Name: "Perry Ellis", Address: "5000 Arizona Mills Cir, Ste 360, Arizona '
 'Mills", City: Tempe, State: AZ, Postal code: 85282, RATING: 4.5, Number of '
 'Reviews: 8')
('Name: "J Stanley Reidhead, DDS", Address: "2076 E Southern Ave, Ste C-103", '
 'City: Tempe, State: AZ, Postal code: 85282, RATING: 5.0, Number of Reviews: '
 '3')
('Name: "Sharon Layman - State Farm Insurance Agent", Address: "4411 S Rural '
 'Rd, Ste 104", City: Tempe, State: AZ, Postal code: 85282, RATING: 4.0, '
 'Number of Reviews: 5')
('Name: "Palo Verde Lounge", Address: "1015 W Broadway Rd", City: Tempe, '
 'State: AZ, Postal code: 85282, RATING: 4.0, Number of Reviews: 55')
('Name: "Club Reef", Address: "1829 E Southern Ave", City: Tempe, State: AZ, '
 'Postal code: 85282, RATING: 4.0, Number of Reviews: 12')
('Name: "Ophthalmic Surgeons and Physicians", Address: "3200 S Country Club '
 'Way", City: Tempe, State: AZ, Postal code: 85282, RATING: 4.0, Number of '
 'Reviews: 8')